services:
  api-gateway:
    build: .
    ports:
      - "5188:5188"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__RedisConnection=localhost:6380
      - ConnectionStrings__ProductEngineGrpcConnection=http://localhost:9091
    depends_on:
      - redis
    networks:
      - redis_network
  redis:
    image: redis
    container_name: api-gateway-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - redis_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    tty: true
    stdin_open: true

networks:
  redis_network:
    driver: bridge
